name: Auto PR

on:
  push:
    branches:
      - "feature/*"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ github.head_ref }}"
          destination_branch: "main"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Pull Request for Changes to Main"
          pr_body: "Automated pull request from ${{ github.head_ref }} to main."
          pr_label: "auto-pr"
