# name: Student pipeline

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "20" # Specify the Node.js version

#       - name: Install dependencies (StudentClassAttendanceTracker)
#         run: |
#           cd StudentClassAttendanceTracker
#           npm install
#       - name: Build (StudentClassAttendanceTracker)
#         run: |
#           cd StudentClassAttendanceTracker
#           npm run build
#           # Other build steps if necessary
#       - name: List output of build
#         run: ls -l StudentClassAttendanceTracker

#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main' && github.event_name == 'push'

#     steps:
#       - uses: actions/checkout@v2
#       - name: List directory structure
#         run: ls -R StudentClassAttendanceTracker

#       - name: Deploy to Server
#         uses: easingthemes/ssh-deploy@v2.1.5
#         with:
#           S_SSH_PRIVATE_KEY: ${{ secrets.S_SSH_PRIVATE_KEY }} # Replace with the name of your secret
#           SOURCE: "StudentClassAttendanceTracker/dist/" # Correct path to the build outputs
#           REMOTE_HOST: ${{ secrets.REMOTE_HOST }} # Replace with the name of your secret
#           S_REMOTE_USER: ${{ secrets.S_REMOTE_USER }} # Replace with the name of your secret
#           TARGET: "/var/www/html/"

#       - name: Start Application with PM2
#         run: |
#           echo "${{ secrets.S_SSH_PRIVATE_KEY }}" > ssh_key
#           chmod 600 ssh_key
#           ssh -i ssh_key ${{ secrets.S_REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "source /home/johannes/.nvm/nvm.sh && /home/johannes/.nvm/versions/node/v21.4.0/bin/pm2 start Main/StudentServer/index.js --name tea --force"
#       - name: Notify of Deployment
#         run: |
#           echo "Deployment complete"
