# name: Teacher pipeline

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "20" # Specify the Node.js version

#       - name: Install dependencies (ClassAttendanceTracker)
#         run: |
#           cd ClassAttendanceTracker
#           npm install
#       - name: Build (ClassAttendanceTracker)
#         run: |
#           cd ClassAttendanceTracker
#           npm run build
#       - name: List output of build
#         run: ls -l ClassAttendanceTracker

#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main' && github.event_name == 'push'

#     steps:
#       - uses: actions/checkout@v2
#       - name: List directory structure
#         run: ls -R ClassAttendanceTracker

#       - name: Deploy to Server
#         uses: easingthemes/ssh-deploy@v2.1.5
#         with:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#           SOURCE: "ClassAttendanceTracker/dist/"
#           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#           REMOTE_USER: ${{ secrets.REMOTE_USER }}
#           TARGET: "/var/www/html/"

#       - name: Start Application with PM2
#         run: |
#           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
#           chmod 600 ssh_key
#           ssh -i ssh_key ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "source /home/johannes/.nvm/nvm.sh && /home/johannes/.nvm/versions/node/v21.4.0/bin/pm2 start Main/Server/index.js --name tea --force"
#       - name: Notify of Deployment
#         run: |
#           echo "Deployment complete"
