name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          # Comment out or remove the cache line to disable caching
          # cache: 'npm'

      - name: Install and test Server
        working-directory: Server
        run: |
          npm ci
          npm test

      - name: Install and test ClassAttendanceTracker
        working-directory: ClassAttendanceTracker
        run: |
          npm ci
          npm test
