name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
      - run: npm ci
      - run: npm test # runs "npm run build"
