name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Transfer Repository Files to Azure VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          rsync -avz -e "ssh -i ssh_key -o StrictHostKeyChecking=no" --exclude='.git' --exclude='node_modules' ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/Main/ClassAttendanceTracker
          rm ssh_key

      - name: SSH and Build on Azure VM
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd Main/ClassAttendanceTracker
            git pull
            npm install
            npm run build
          EOF

      - name: Deploy Built Files to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "Main/ClassAttendanceTracker/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/var/www/html/"

      - name: Start Application with PM2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "source /home/johannes/.nvm/nvm.sh && /home/johannes/.nvm/versions/node/v21.4.0/bin/pm2 start Main/Server/index.js --name tea"

      - name: Notify of Deployment
        run: |
          echo "Deployment complete"
